### ISSUE TITLE
Set up product and projects for Eclipse installer

### ISSUE THREAD

**Issue by fsteeg** [culturegraph/metafacture-ide#42]
- To assist when editing the morph file, the IDE should include the Eclipse XML editor
- It should be set up to include the morph and morph-test XSDs for validation and content assist
- The IDE should contain other features used for real world metafacture usage (JDT, Maven, Egit)

**Comment by fsteeg** [comment]
- [x] Basic setup product with XML editor for Eclipse installer
- [ ] Publish current version as 0.2.0 to http://lobid.org/download/tools/p2
- [ ] Add Xturtle, GEF, m2e to setup product
- [ ] Investigate standalone product creation with Oomph

**Comment by fsteeg** [comment]
Ready for review, see: https://github.com/culturegraph/metafacture-ide/blob/42-setup/MANUAL.textile

Assigning only @dr0i (team member here), but should be reviewed by @acka47 and @ChristophEwertowski too (sent invites for collaboration) to see if this works and makes sense for all three of you.

**Comment by dr0i** [comment]
very good +1

**Comment by acka47** [comment]
I tried to set the environment up as described in https://github.com/culturegraph/metafacture-ide/blob/42-setup/MANUAL.textile. During the setup tasks execution is cancelled, though. Here is the output:

```
Executing bootstrap tasks
Renamed existing configuration folder to /home/acka47/ide-neon/eclipse/configuration.1496829867613
Java(TM) SE Runtime Environment 1.8.0_131-b11
Product user.products.org.culturegraph.mf.ide.neon
Bundle org.eclipse.oomph.setup 1.7.0.v20170224-1311, build=2932, branch=cc66c993507ade50e4b3a824a3adb4e94c4ac25f
Bundle org.eclipse.oomph.setup.core 1.7.0.v20170301-0747, build=2932, branch=cc66c993507ade50e4b3a824a3adb4e94c4ac25f
Bundle org.eclipse.oomph.setup.installer 1.7.0.v20170305-1123, build=2932, branch=cc66c993507ade50e4b3a824a3adb4e94c4ac25f
Bundle org.eclipse.oomph.setup.p2 1.7.0.v20170217-1051, build=2932, branch=cc66c993507ade50e4b3a824a3adb4e94c4ac25f
Performing P2 Director (Metafacture IDE (Neon))
Offline = false
Mirrors = true
Resolving 19 requirements from 6 repositories to /home/acka47/ide-neon/eclipse
Requirement org.eclipse.platform.ide
Requirement org.eclipse.platform.feature.group
Requirement org.eclipse.rcp.feature.group
Requirement org.culturegraph.mf.ide.sdk.feature.group
Requirement org.eclipse.wst.xml_ui.feature.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.egit.feature.group
Requirement org.eclipse.jdt.feature.group
Requirement org.eclipse.gef4.dot.sdk.feature.group
Requirement de.itemis.tooling.xturtle.feature.feature.group
Requirement org.eclipse.oomph.setup.sdk.feature.group
Requirement org.sonatype.m2e.buildhelper.feature.feature.group
Requirement org.sonatype.m2e.antlr.feature.feature.group
Requirement com.ianbrandt.tools.m2e.mdp.feature.feature.group
Requirement org.eclipse.mylyn.wikitext_feature.feature.group
Requirement org.eclipse.mylyn.github.feature.feature.group
Requirement org.eclipse.oomph.setup.mylyn.feature.group
Requirement org.eclipse.mylyn.tasks.core
Requirement org.eclipse.mylyn.tasks.ui
Repository http://download.eclipse.org/releases/neon
Repository http://lobid.org/download/tools/p2
Repository http://xturtle.nittka.de/snapshot
Repository http://coderplus.com/m2e-update-sites/maven-dependency-plugin
Repository https://repository.sonatype.org/content/repositories/forge-sites/m2e-extras/0.15.0/N/0.15.0.201206251206
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Adding repository http://download.eclipse.org/releases/neon
Adding repository http://lobid.org/download/tools/p2
Adding repository http://xturtle.nittka.de/snapshot
Adding repository https://repository.sonatype.org/content/repositories/forge-sites/m2e-extras/0.15.0/N/0.15.0.201206251206
Adding repository http://coderplus.com/m2e-update-sites/maven-dependency-plugin
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Calculating requirements and dependencies.
Computing prerequisite plan
Collecting 2 artifacts from http://lobid.org/download/tools/p2
Downloading org.eclipse.platform_root
Downloading org.eclipse.rcp_root
Collected 2 artifacts for http://lobid.org/download/tools/p2 in 0.102s
Collecting 1 artifacts from http://download.eclipse.org/releases/neon
Downloading org.eclipse.platform.ide.executable.gtk.linux.x86_64
Collected 1 artifacts for http://download.eclipse.org/releases/neon in 1.209s
The engine operation was cancelled and the changes are being rolled back.
Took 53 seconds.
Task execution was canceled.
Press Back to choose different settings or Cancel to abort.
```

Here is a screenshot of the task list:

![tasks](https://user-images.githubusercontent.com/160292/26873841-8a4b86b2-4b7b-11e7-9d1c-82b8c14665e1.png)

**Comment by fsteeg** [comment]
Hm, could it be that you did not confirm one or some of the licenses? In particular, in one screen you have to select a checkbox and then click "Accept selected" or similar. Could you re-run the installation and make sure you confirm all dialogs?

**Comment by fsteeg** [comment]
This is the dialog I mean:

![confirm-certificate](https://user-images.githubusercontent.com/128229/26882980-37e581b8-4b9c-11e7-8e0e-177efda9e0f8.png)

**Comment by fsteeg** [comment]
I've added a screenshot and mentioned the certificate step:
https://github.com/culturegraph/metafacture-ide/blob/42-setup/MANUAL.textile

**Comment by acka47** [comment]
I think I confirmed the license but maybe too late (the pop-up was open for some time). Now it worked but I can not see the metafacture projects. Will try again tomorrow on the desktop pc in my hbz office.

**Comment by ChristophEwertowski** [comment]
After selecting the four projects I get authentication failures.
```
Cloning Git repo git@github.com:culturegraph/metafacture-core.git to /home/christoph/metafacture-core-git-master/git/metafacture-core
java.lang.Exception: org.eclipse.jgit.api.errors.TransportException: git@github.com:culturegraph/metafacture-core.git: Auth fail
   at 
...
Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:culturegraph/metafacture-core.git: Auth fail
   at  
...
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:culturegraph/metafacture-core.git: Auth fail
  at
...
Caused by: com.jcraft.jsch.JSchException: Auth fail
  at
...
ERROR: org.eclipse.oomph.setup.core code=0 org.eclipse.jgit.api.errors.TransportException: git@github.com:culturegraph/metafacture-core.git: Auth fail
java.lang.Exception: org.eclipse.jgit.api.errors.TransportException: git@github.com:culturegraph/metafacture-core.git: Auth fail
  at
...
Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:culturegraph/metafacture-core.git: Auth fail
  at
...
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:culturegraph/metafacture-core.git: Auth fail
  at
...
Caused by: com.jcraft.jsch.JSchException: Auth fail
  at
```

**Comment by fsteeg** [comment]
@ChristophEwertowski I've added details on the GitHub repo setup, could you try again?

@acka47 I guess your problem (missing projects) was caused by the same issue.

https://github.com/culturegraph/metafacture-ide/blob/42-setup/MANUAL.textile

**Comment by acka47** [comment]
I now made it through the installation and all the projects are there. \o/ Now somebody must show me why I should use it. :-)

**Comment by ChristophEwertowski** [comment]
At using the content assist I get the following exceptions (and the help text with input, output, description isn't shown):
```
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTError: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)])
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4536)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4154)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: org.eclipse.swt.SWTError: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]
	at org.eclipse.swt.SWT.error(SWT.java:4559)
	at org.eclipse.swt.browser.Mozilla.initMozilla(Mozilla.java:2237)
	at org.eclipse.swt.browser.Mozilla.create(Mozilla.java:691)
	at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
	at org.eclipse.jface.internal.text.html.BrowserInformationControl.createContent(BrowserInformationControl.java:216)
	at org.eclipse.jface.text.AbstractInformationControl.create(AbstractInformationControl.java:456)
	at org.eclipse.jface.internal.text.html.BrowserInformationControl.<init>(BrowserInformationControl.java:182)
	at org.eclipse.xtext.ui.editor.hover.html.XtextBrowserInformationControl.<init>(XtextBrowserInformationControl.java:24)
	at org.culturegraph.mf.ide.ui.contentassist.FluxProposalProvider$FluxCompletionProposal$1.doCreateInformationControl(FluxProposalProvider.java:80)
	at org.eclipse.jface.text.AbstractReusableInformationControlCreator.createInformationControl(AbstractReusableInformationControlCreator.java:43)
	at org.eclipse.jface.text.AbstractInformationControlManager.getInformationControl(AbstractInformationControlManager.java:831)
	at org.eclipse.jface.text.AbstractInformationControlManager.internalShowInformationControl(AbstractInformationControlManager.java:1181)
	at org.eclipse.jface.text.AbstractInformationControlManager.presentInformation(AbstractInformationControlManager.java:1163)
	at org.eclipse.jface.text.AbstractInformationControlManager.setInformation(AbstractInformationControlManager.java:428)
	at org.eclipse.jface.text.contentassist.AdditionalInfoController.computeInformation(AdditionalInfoController.java:550)
	at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1144)
	at org.eclipse.jface.text.AbstractInformationControlManager.showInformation(AbstractInformationControlManager.java:1134)
	at org.eclipse.jface.text.contentassist.AdditionalInfoController.showInformation(AdditionalInfoController.java:536)
	at org.eclipse.jface.text.contentassist.AdditionalInfoController$1.showInformation(AdditionalInfoController.java:483)
	at org.eclipse.jface.text.contentassist.AdditionalInfoController$Timer$7.run(AdditionalInfoController.java:367)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 24 more
```

**Comment by acka47** [comment]
I think a toc should be added to the user guide as it has gotten very long. Also, I think the features of the IDE should be listed more prominently so that people who are interested can easily decide whether they want to install it. Currently, the features are especially listed in the [Flux-driven transformations paragraph](https://github.com/culturegraph/metafacture-ide/blob/42-setup/MANUAL.textile#flux-driven-transformations):

> The Metafacture IDE provides syntax coloring and syntax checking, semantic validation, content assist (CTRL+Space), an outline view, workflow visualization, and a launcher to execute Flux files (see screenshot and the Features section below). The IDE also contains editors for many common and not so common file formats, like XML, many kind of lightweight markup formats (Markdown, Textile, etc.), Turtle files, etc.

In the Java-driven transformations paragraph it also reads:

> The Metafacture IDE integrates the Eclipse Java Development tools and other plugins, e.g. for Maven, Git, and GitHub integration.

There are two options:

1. Add this to the readme
2. Move this on top of the user guide

**Comment by acka47** [comment]
Collecting some suggestions for improvement:

- Correct URI for `http://lobid.org/vocab/lobid#fulltextOnline` is `http://purl.org/lobid/lv#fulltextOnline`.
- "clicking" instead of "double-clicking" in:
> The elements in the Outline view are linked to the corresponding parts of you Flux file in the editor: double-clicking the elements will highlight the corresponding text.

**Comment by ChristophEwertowski** [comment]
The solution for the missing tip content assist was to execute:
`apt-get install libwebkitgtk-1.0-0` as written in the eclipse forum.

**Comment by fsteeg** [comment]
Added remaining feedback, pushed to master, replaced wiki with links to new files. Closing.
